# Generated by Django 5.0 on 2024-05-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('username', models.CharField(max_length=10000, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('pin', models.CharField(max_length=4)),
                ('initial_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
