# Generated by Django 5.0 on 2024-05-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Withdrawal', 'withdrawal'), ('Deposit', 'deposit'), ('Transfer', 'transfer')], default='withdrawal', max_length=100),
        ),
    ]
