# Generated by Django 5.0 on 2024-05-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Withdrawal', 'withdrawal'), ('Deposit', 'deposit'), ('Transfer In', 'transfer In'), ('Transfer Out', 'transfer Out')], max_length=100),
        ),
    ]
